### ISSUE TITLE
New Version of Docker

### ISSUE THREAD

**Issue by mappuji** [ole-vi/treehouse-builder#102]
For production we need multistage build an its need Docker version 17.05 or higher

The resulted image with this feature will be used in our docker builder machine `docker.ole.org` this way we will catch bug early because we eat our own dogfood.

references:
- [Multistage build](https://docs.docker.com/engine/userguide/eng-image/multistage-build/)
- [Install docker with official way](https://docs.docker.com/engine/installation/linux/docker-ce/debian/#uninstall-old-versions)

It is related to https://github.com/ole-vi/planet/pull/86

**Comment by i5o** [comment]
https://github.com/ole-vi/treehouse-builder/commit/dec44d3f60c816d28818eedd4d7f363ddada1e87
