### ISSUE TITLE
create a planet autorunonce script

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#108]
analog to BeLL-Apps:
- with rtc - https://gist.github.com/dogi/a3e9a0612d07436d5f7d2b3bb2051be3
- without rtc https://gist.github.com/dogi/3a82a35b7f4adacac46e3eac08e6d9c0

**Comment by ajGingrich** [comment]
gist created [here](https://gist.github.com/ajGingrich/e81cbd292281c10b7b0a56f256fee55b)
