### ISSUE TITLE
add sshkeys on user pi and root

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#13]
`ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArMkyotKz1J5+Kux3ToBNe+X3Qm+6WzTXflEEeOWdmxDZ5f5le7Ujes81ybRnavWSNR2TGr1evigE7vGsxHm2aEeR0YICWR24lPcJ2FUROmEdwn2OjDzh1YcKJDNvlMzXt1x0dNeEkSisHpk6p5RJ7OfCtyD/OjKhGyajbxS/n3RDSMgND46M7AiiaaIzlut3D09Gyhd93t16NTyR9Ej1RRRk8z9of3qLwhC1AqVJpSkuWn9+q111AfljsVZCHHDLw0+j7NIntk5x+yzrl2QQECNEaPpm1Pt4gmLG2nnrNjPAtrjWIfyWfhdSbgk/QscAE2XpCYoSFBW9d8bdIVMfSw== stefan@unterhauser.name`

or

https://github.com/dogi.keys

Think best is to get all keys by adding our github name and just curl ing them by a loop

**Comment by paulbert** [comment]
GitHub API documentation to get members of the ole-vi organization by curl:

https://developer.github.com/v3/orgs/members/

With that we should be able to get all usernames, and then loop a bunch of curl github.com/<username>.keys (ex: https://github.com/paulbert.keys)

**Comment by 0xdaf** [comment]
fixed in 3f17997
