### ISSUE TITLE
fix docker images "hack"

### ISSUE THREAD

**Issue by xyb994** [ole-vi/treehouse-builder#133]
docker image pull is not working well on raspberry pi right now, we are currently having
https://github.com/ole-vi/treehouse-builder/blob/master/scripts.d/30_docker.sh and
https://github.com/ole-vi/pirateship/blob/master/lib/docker.js
as workaround.

– dogi

**Comment by dogi** [comment]
https://github.com/ole-vi/treehouse-builder/pull/136
