### ISSUE TITLE
Script in /boot which gets started at boot

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#2]
We are looking for two different script types to be started at boot:
- [x] `/boot/autorun`
- [x] `/boot/autorun.sh`
- [x] `/boot/autorun.txt`
- [ ] `/boot/autorunonce`
- [ ] `/boot/autorunonce.sh`
- [ ] `/boot/autorunonce.txt`

best would be they got start in a screen session ;)

**Comment by 0xdaf** [comment]
Fixed in master as of 6a8d2a5.
