### ISSUE TITLE
build image on travis and upload to dev.ole.org

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#21]
- [x] get build working on travis
- [x] have travis upload build results to dev.ole.org
- [x] have travis send notifications to gitter

**Comment by 0xdaf** [comment]
I don't think github releases is going to work for us, so let's use dev.ole.org to host instead.

We should do something like this: https://oncletom.io/2016/travis-ssh-deploy/

**Comment by 0xdaf** [comment]
This is working on the deploy branch. We need to make two decisions:

 * When should deployment happen? On tagged commits, or only on certain branches?
 * How should uploaded images be named?

I think using git tags is a nice straightfoward approach. Git tags could be used to name images too, e.g. if the git tag is "release-10", then the deployment code could use it to call the uploaded image treehouse10.img.gz.
