### ISSUE TITLE
<hostname>.local not working

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#58]

**Comment by dogi** [comment]
Aug 31 01:01:06 raspberrypi systemd-hostnamed[1263]: Warning: nss-myhostname is not installed. Changing the local hostname might make it unresolveable. Please install nss-myhostname!

**Comment by mappuji** [comment]
It maybe a good solution (?)
https://learn.adafruit.com/bonjour-zeroconf-networking-for-windows-and-linux/overview

**Comment by dogi** [comment]
`systemctl restart avahi-daemon`
fixed the problem

wonder if we should do it on the end of `pirateship rename <hostname>`
