### ISSUE TITLE
turn off autoimport of couchdb on first boot

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#69]
... trigger it by `pirateship couchdb`

**Comment by dogi** [comment]
this iterates on top of https://github.com/ole-vi/treehouse-builder/issues/40 and

**Comment by i5o** [comment]
- [ ] Setup vagrant to be able to test without the need of download a new image every time
- [ ] Move  _(comment)_ stuff from treehouse-builder without breaking anything
- [ ] Copy that commands/stuff to pirateship couchdb command
- [ ] Limit the command to one use, perhaps a file in the system that prevents it for running?
- [ ] Keep testing

**Comment by i5o** [comment]
progress update: still finishing some changes in vagrant stuff. Shouldn't take long (problems with ssh keys)
