### ISSUE TITLE
pirateship sshkeyadd

### ISSUE THREAD

**Issue by dogi** [ole-vi/treehouse-builder#75]
for root and pi user

**Comment by i5o** [comment]
* for pi and root

**Comment by xyb994** [comment]
- Command to be added — `pirateship sshkeyadd <public_key>`
- It would take one argument — `<public_key>`
- `sshkeyadd.js` would check if `/home/pi/.ssh/authorized_keys` and `/root/.ssh/authorized_keys` exist, if not, it would be created (with 600 right), then `<public_key>` would be appended to the file

@dogi: For next iteration, let the user specify add the key to which user.
